### ISSUE TITLE
Terms link the same as about

### ISSUE THREAD

**Issue by Ryuno-Ki** [vkWeb/inspire-step#5]
Is it on purpose, that „Terms and Privacy” have the same target than „About” in the footer?

**Comment by vkWeb** [comment]
@Ryuno-Ki Noope. Was testing whether `a` has inherited `p`'s color or not.

**Comment by Ryuno-Ki** [comment]
`currentColor` is your friend.

**Comment by vkWeb** [comment]
@Ryuno-Ki Thanks Andre. Learned a new thing!
